# Generated by Django 4.2.7 on 2025-04-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moneyoperation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Денежная операция', 'verbose_name_plural': 'Денежные операции'},
        ),
        migrations.RemoveField(
            model_name='moneyoperation',
            name='operation_date',
        ),
        migrations.AlterField(
            model_name='moneyoperation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи'),
        ),
    ]
