# Generated by Django 4.2.7 on 2025-04-25 13:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dds', '0002_alter_moneyoperation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyoperation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания записи'),
        ),
    ]
