# Generated by Django 4.2.7 on 2025-04-26 06:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dds', '0003_alter_moneyoperation_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyoperation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.localdate, verbose_name='Дата создания записи'),
        ),
    ]
